---
title: "Lab 07 - Truth-O-Meter"
author: "Insert your name here"
date: "Insert date here"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(skimr)
```

```{r load-data, message = FALSE, eval = FALSE}

# Remove eval = FALSE or set it to TRUE once data is ready to be loaded

fact_checks_lie <- read_csv("data/fact_checks_lie.csv") # <<< you just created this .csv in the R scripts
fact_checks_truth <- read_csv("data/fact_checks_truth.csv") # <<< you just created this .csv in the R scripts

```

### Exercise 11

```{r add-new-variables-and-append}

fact_checks_lie <- fact_checks_lie %>%
  replace_with_function("___" = "___") # <<< create a new column that indicates these are lies

fact_checks_truth <- fact_checks_truth %>%
  replace_with_function("___" = "___") # <<< create a new column that indicates these are truths

fact_checks <- replace_with_function() # <<< combine the two data frames 

```

### Exercise 12

```{r separate-description-date-1, error = TRUE}

fact_checks <- fact_checks %>%
  replace_with_function(description, into = c("part1", "part2"), sep = "on ") 

## STOP HERE and inspect the "fact_checks" data frame to see what is going on with "part1" and "part2" 
```

```{r separate-description-date-2, error = TRUE}

fact_checks <- fact_checks %>%
  separate(part2, into = c("part1", "part2"), sep = " in")

## STOP HERE and inspect the "fact_checks" data frame to see what is going on with "part1" and "part2" 
```

```{r separate-description-date-3}

fact_checks <- fact_checks %>%
  rename(date = "___") %>%
  select(-part2)

```

### Exercise 13

Remove this text, and add your answer for Exercise 1 here.
Add code chunks as needed.
Don't forget to label your code chunk.
Do not use spaces in code chunk labels.

