---
title: "Homework Module 8"
author: "Your name here"
output: html_notebook
---

## Warming up


```{r load-packages, message = FALSE, eval = TRUE}
library(tidyverse)
library(modelr)
```


## Exercises

### Exercise 1

Add your code and text responses for the exercise here.

### Exercise 2

Add your code and text responses for the exercise here.

### Exercise 3

Add your code and text responses for the exercise here.

### Exercise 4

Add your code and text responses for the exercise here.

### Exericse 5

Add your code and text responses for the exercise here.

### Exercise 6

Add your code and text responses for the exercise here.

### Exercise 7

Add your code and text responses for the exercise here.

### Exercise 8

Add your code and text responses for the exercise here.

### Exericse 9

Add your code and text responses for the exercise here.

### Exercise 10

Add your code and text responses for the exercise here.

### Exercise 11

Add your code and text responses for the exercise here.

### Exercise 12

Add your code and text responses for the exercise here.

### Exercise 13

Add your code and text responses for the exercise here.

### Exercise 14

Add your code and text responses for the exercise here.

### Exercise 15

Add your code and text responses for the exercise here.

