---
title: "Lab 08a - Heights, weights, and lines--oh my!"
author: "Insert your name here"
date: "Insert date here"
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(modelr)

source("starter/m8-helpers.R")
```

```{r load-data, message=FALSE}
simd1 <- read_csv("data/simd1.csv")
simd2 <- read_csv("data/simd2.csv")
howell <- read_csv("data/howell1.csv")
```

## Exercises


### Exercise 1

Draw on graph paper.

### Exercise 2

Remove this text, and add your answer for Exercise 2 here.


### Exercise 3

```{r, echo=T}
intercept1 <- 0
slope1 <- 0
plot_reg_rss(simd1$x, simd1$y, intercept1, slope1)
```

Remove this text, and add your answer for Exercise 3 here.

### Exercise 4

```{r, echo=T}
intercept2 <- 0
slope2 <- 0
plot_reg_rss(simd2$x, simd2$y, intercept2, slope2)
```

Remove this text, and add your answer for Exercise 4 here.

### Exercise 5

...

### Exercise 6

...

### Exercise 7

...


### Exercise 8

...


### Exercise 9

...


### Exercise 10

...