---
title: "HW 04 - College Majors"
author: "Insert your name here"
date: "Insert date here"
output: html_document
---

## Load packages and data

```{r, include=F}
library(tidyverse)
library(scales)
library(fivethirtyeight)
```

## Exercises

### Exercise 1

Remove this text, and add your answer for Exercise 1 here including any code needed.

### Exercise 2

Remove this text, and add your answer for Exercise 2 here including any code needed.

### Exercise 3

Remove this text, and add your answer for Exercise 3 here including any code needed.

### Exercise 4

Remove this text, and add your answer for Exercise 4 here including any code needed.


### Exercise 5

Remove this text, and add your answer for Exercise 5 here including any code needed.


### Exercise 6

Remove this text, and add your answer for Exercise 6 here including any code needed.


### Exercise 7

Remove this text, and add your answer for Exercise 7 here including any code needed.


### Exercise 8

Remove this text, and add your answer for Exercise 8 here including any code needed.

