project:
  title: "Code-alongs"
  # output-dir: ../../docs/code-along
  # output-dir: ../../docs/code-along/classwork

format:
  html:
    theme: flatly
    highlight: tango
    # css: styles.css
    self-contained: true
    grid:
      margin-width: 350px   
  pdf: default
execute:
  echo: fenced
reference-location: margin        
citation-location: margin         
knitr:
  opts_chunk: 
    # eval: FALSE
    message: FALSE
    warning: FALSE
#     out.width: "80%"
#     fig.asp: 0.618
#     fig.width: 8
#     dpi: 300

