---
title: '&#32;'
output:
  html_document
---

```{r, include=F, dependson="setup.R"}
## Exam 1 specific

library(tidyverse)
library(nycflights13)

set.seed(42)

flights <- flights %>% 
  slice_sample(prop=.35)
```


> Let's say we wanted to calculate the route (airport to airport) with the greatest average delay so we could avoid ever traveling it. We'll just ignore missing values. Which of these would be the right first steps to accomplish this?

```{r, include=F}
flights %>% 
  group_by(origin, dest) %>% 
  summarize(mean_arr_delay = mean(arr_delay, na.rm=TRUE))

# flights %>% 
#   group_by(origin, dest) %>% 
#   summarize(num_flights = n_distinct(flight))
# 
# flights %>% 
#   group_by(origin, dest, flight) %>% 
#   summarize(n = n()) %>% 
#   summarize(num_flights = sum(n()))
```


A)
```
flights %>% 
  group_by(origin, dest) %>% 
  summarize(mean_arr_delay = mean(arr_delay, na.rm=TRUE))
```
B) 
```
flights %>% 
  group_by(origin) %>% 
  summarize(mean_arr_delay = mean(arr_delay))
```
C)
```
flights %>% 
  group_by(dest) %>% 
  summarize(mean_arr_delay = mean(arr_delay, na.rm=TRUE))
```
D)
```
flights %>% 
  group_by(origin, dest) %>% 
  summarize(max_arr_delay = max(arr_delay, na.rm=TRUE))
```
