---
title: '&#32;'
output:
  html_document:
    df_print: paged
---

```{r, include=F, dependson="setup.R"}
## Exam 1 specific

library(tidyverse)
library(nycflights13)

set.seed(42)

flights <- flights %>% 
  slice_sample(prop=.35)
```


Which of the code chunks would complete the code needed to create the plot below?

```{r, echo=T, eval=F}
flights %>% 
  mutate(
    dep_time_bin = cut(sched_dep_time, c(0, 600, 1200, 1800, 2400)),
    arr_delay_bin = cut(arr_delay, c(-Inf, 0, 10, 30, 60, 120, 300, Inf))
    ) %>%
  group_by(dep_time_bin, arr_delay_bin) %>% 
  summarize(n = n()) %>% 
  mutate(prop = n/sum(n)) %>% ...
```

```{r, echo=F}
flights %>% 
  mutate(
    dep_time_bin = cut(sched_dep_time, c(0, 600, 1200, 1800, 2400)),
    arr_delay_bin = cut(arr_delay, c(-Inf, 0, 10, 30, 60, 120, 300, Inf))
    ) %>%
  group_by(dep_time_bin, arr_delay_bin) %>% 
  summarize(n = n()) %>% 
  mutate(prop = n/sum(n)) %>% 
  ggplot(aes(x=dep_time_bin, y = prop, fill = arr_delay_bin)) +
  geom_col() +
  scale_fill_viridis_d()
```



A) 
```
  ggplot(aes(x=dep_time_bin, y = prop, color = arr_delay_bin)) +
  geom_hist() +
  scale_fill_viridis_d()
```
B)
```
  ggplot(aes(x=dep_time_bin, y = prop, color = arr_delay_bin)) +
  geom_col()
```
C)
```
  ggplot(aes(x=dep_time_bin, y = prop, fill = arr_delay_bin)) +
  geom_col() +
  scale_fill_viridis_d()
```
D) 
```
  ggplot(aes(x=dep_time_bin, y = prop, color = arr_delay_bin)) +
  geom_bar(stat="count") +
  scale_fill_viridis_d()
```