---
title: '&#32;'
output:
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: console
---

```{r, include=F, dependson="setup.R"}

library(tidyverse)
library(nycflights13)

set.seed(42)

flights <- flights %>% 
  slice_sample(prop=.35)

```

> Based on the last question, we created a new data frame, which I called `flights_weather_avg`, that looks like the below:

```{r, eval=T, echo=F, message=F}
flights_weather_avg <- inner_join(flights, weather, by = c("year", "month", "day", "origin", "hour")) %>% select(month, day, origin, dep_delay, wind_gust) %>%
  group_by(month, day, origin) %>%
  summarize(
    avg_dep_delay = mean(dep_delay, na.rm = TRUE),
    avg_wind_gust = mean(wind_gust, na.rm = TRUE)
  )
flights_weather_avg
```

> With this data I can generate the following plot:

```{r, echo=F, message=F, warning=F}
ggplot(flights_weather_avg, aes(x = avg_wind_gust, y = avg_dep_delay)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = lm) +
  facet_wrap(~origin, scales = "free") +
  labs(x = "Average Wind Gust Speed (mph)", y = "Average Delay (min)")
```

> What is the code that I used? Please select from one of the following options:

A) 
```
ggplot(flights_weather_avg, aes(x = avg_wind_gust, y = avg_dep_delay)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = lm) +
  facet_wrap(~origin, scales = "free") +
  labs(x = "Average Wind Gust Speed (mph)", y = "Average Delay (min)")
```

B)
```
ggplot(flights_weather_avg, aes(x = avg_wind_gust, y = avg_dep_delay)) +
  geom_point(alpha = 0.3) +
  facet_wrap(~origin, method = "lm") +
  labs(x = "Average Wind Gust Speed (mph)", y = "Average Delay (min)")
```

C) 
```
ggplot(flights_weather_avg, aes(x = avg_wind_gust, y = avg_dep_delay)) +
  geom_scatter(alpha = 0.3) +
  geom_line(x ~ y) +
  facet_wrap(~origin, scales = "free") +
  labs(x = "Average Wind Gust Speed (mph)", y = "Average Delay (min)")
```

D)
```
ggplot(flights_weather_avg, aes(x = avg_wind_gust, y = avg_dep_delay)) +
  geom_scatter(alpha = 0.3) +
  geom_line(method = lm) +
  facet_wrap(~origin) +
  labs(x = "Average Wind Gust Speed (mph)", y = "Average Delay (min)")
```




