---
title: "Lab 03 - Nobel laureates"
author: "Insert your name here"
date: "Insert date here"
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("labs/data/nobel.csv")

# NOTE: below will also load in the file. This is because `read_csv` can also pull files stored online. 
# nobel <- read_csv("https://asucbi.github.io/data/nobel.csv")
```

## Exercises

### Exercise 1

```{r obs-vars}

nrow(nobel)
ncol(nobel)

```


### Exercise 2

```{r new-df}

nobel_living <- nobel %>% 
  filter(
    !is.na(country),
    gender != "org",
    is.na(died_date)
  )

```
```{r prep-ex3}

nobel_living <- nobel_living %>%
  mutate(
    country_us = if_else(country == "USA", "USA", "Other")
  )

nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))


```
### Exercise 3

```{r bar-plot}

nobel_living_science %>%
  ggplot(aes(x=country_us, fill=country_us)) +
  geom_bar() + 
  facet_wrap(~category) + 
  coord_flip()

```


### Exercise 4

```{r born-us}

nobel_living_science <- nobel_living_science %>%
  mutate(
    born_country_us = if_else(born_country_code == "US", "USA", "Other")
  )

```

### Exercise 5

```{r us-plot}

nobel_living_science %>%
  ggplot(aes(x=country_us, fill=born_country_us)) +
  geom_bar() + 
  facet_wrap(~category) + 
  coord_flip() +
  labs(x = "Country Award Received", y = "Count", fill = "Country Born")

```


### Exercise 6

...
```{r nobelists-born}

nobel_living_science %>% 
  filter(country_us == "USA" & 
           born_country_us == "Other") %>% 
  group_by(born_country) %>% 
  count(sort = TRUE)

```
